# releans_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReleansApi
  # Response2002 Model.
  class Response2002 < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :balance

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['balance'] = 'balance'
      @_hash
    end

    def initialize(balance = nil)
      @balance = balance
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      balance = hash['balance']

      # Create object from extracted values.
      Response2002.new(balance)
    end
  end
end
