# releans_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReleansApi
  # Response2001 Model.
  class Response2001 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sender_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :phone_number

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['sender_name'] = 'senderName'
      @_hash['phone_number'] = 'phoneNumber'
      @_hash['status'] = 'status'
      @_hash
    end

    def initialize(id = nil,
                   sender_name = nil,
                   phone_number = nil,
                   status = nil)
      @id = id
      @sender_name = sender_name
      @phone_number = phone_number
      @status = status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      sender_name = hash['senderName']
      phone_number = hash['phoneNumber']
      status = hash['status']

      # Create object from extracted values.
      Response2001.new(id,
                       sender_name,
                       phone_number,
                       status)
    end
  end
end
