# releans_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReleansApi
  # BalanceController
  class BalanceController < BaseController
    @instance = BalanceController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # Get your available balance
    # @param [String] accept Required parameter: Example:
    # @return Response2002 response from the API call
    def get_balance(accept)
      # Prepare query url.
      _path_url = '/balance'
      _query_builder = Configuration.get_base_uri
      _query_builder << _path_url
      _query_url = APIHelper.clean_url _query_builder

      # Prepare headers.
      _headers = {
        'Accept' => accept
      }

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url,
        headers: _headers
      )
      OAuth2.apply(_request)
      _context = execute_request(_request)
      validate_response(_context)

      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body)
      Response2002.from_hash(decoded)
    end
  end
end
