# releans_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReleansApi
  #  releans_api client class.
  class ReleansApiClient
    # Singleton access to message controller.
    # @return [MessageController] Returns the controller instance.
    def message
      MessageController.instance
    end

    # Singleton access to sender controller.
    # @return [SenderController] Returns the controller instance.
    def sender
      SenderController.instance
    end

    # Singleton access to balance controller.
    # @return [BalanceController] Returns the controller instance.
    def balance
      BalanceController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(o_auth_access_token: nil)
      Configuration.o_auth_access_token = o_auth_access_token if
        o_auth_access_token
    end
  end
end
